### ISSUE TITLE
Uncaught (in promise) RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by fodurrr** [zeit/next-site#103]
Hi,

I just started to try out Next.js

In Using Shared Components lessons I get the following strange error in chrome console when I click on the About page.

Therefore I cannot go further to try Next.js :(((

Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at Generator.invoke [as _invoke] (http://localhost:3000/_next/1507463501167/main.js:8788:19)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/_next/1507463501167/main.js:8610:21)
    at step (http://localhost:3000/_next/1507463501167/main.js:4302:30)
    at http://localhost:3000/_next/1507463501167/main.js:4320:14
    at new Promise (<anonymous>)
    at new F (http://localhost:3000/_next/1507463501167/main.js:175:28)
    at Object.<anonymous> (http://localhost:3000/_next/1507463501167/main.js:4299:12)
    at Object.renderError (http://localhost:3000/_next/1507463501167/main.js:20108:18)
    at Object.module.exports._ReactReconciler2.default.mountComponent (http://localhost:3000/_next/1507463501167/main.js:15543:12)
    at ReactDOMComponent.mountChildren (http://localhost:3000/_next/1507463501167/commons.js:12087:44)

I refresh the page then the dev server exits with the following error:
npm ERR! code ELIFECYCLE
npm ERR! errno 3221225725
npm ERR! hello-next@1.0.0 dev: `next`
npm ERR! Exit status 3221225725
npm ERR!
npm ERR! Failed at the hello-next@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fodur\AppData\Roaming\npm-cache\_logs\2017-10-08T11_54_58_352Z-debug.log

Please see attached files.

[hello-next.zip](https://github.com/arunoda/learnnextjs-content/files/1366848/hello-next.zip)
[2017-10-08T11_54_58_352Z-debug.log](https://github.com/arunoda/learnnextjs-content/files/1366850/2017-10-08T11_54_58_352Z-debug.log)

**Comment by Tomekmularczyk** [comment]
@fodurrr maximum call stack size is caused by the `About` component rendering itself infinitetly:

```
const About = () => (
  <div>
    <About />
    <p>This is the about page</p>
  </div>
);
```

If that has been an issue with the docs, they [are correct now](https://nextjs.org/learn/basics/using-shared-components/using-the-header-component).

**Comment by timneutkens** [comment]
I never knew you could do infinite loops in React components 😅😂 

Thanks for checking this out @Tomekmularczyk, could you send me a message on https://twitter.com/timneutkens / https://spectrum.chat/users/timneutkens
